<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net10.0-windows</TargetFramework>
	 <SignAssembly>true</SignAssembly>
	 <AssemblyOriginatorKeyFile>D:\Users\Dale\source\repos\LinqToLdap\LinqToLdap.Tests\linqtoldap_tests.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LinqToLdap.Tests\linqtoldap_tests.snk" Link="linqtoldap_tests.snk" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.DirectoryServices.Protocols" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LinqToLdap\LinqToLdap.csproj" />
  </ItemGroup>
</Project>