<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>LinqToLdap</PackageId>
    <Version>1.0.11</Version>
    <Authors>daclark85</Authors>
    <Company>daclark85</Company>
    <Description>LINQ provider built on top of System.DirectoryServices.Protocols for querying and updating LDAP servers.</Description>
    <Product>LINQ to LDAP</Product>
    <PackageTags>LINQ LDAP AD active directory openldap tivoli S.DS.P SDSP</PackageTags>
    <PackageIcon>linqtoldap_logo_small.png</PackageIcon>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/madhatter22/LinqToLdap.git</RepositoryUrl>
    <PackageProjectUrl>https://github.com/daclark85/LinqToLdap</PackageProjectUrl>
    <PackageReleaseNotes>https://github.com/daclark85/LinqToLdap/releases/tag/1.0.0</PackageReleaseNotes>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <NeutralLanguage>en-US</NeutralLanguage>
    <SignAssembly>true</SignAssembly>
    <DelaySign>false</DelaySign>
    <AssemblyOriginatorKeyFile>linqtoldap.snk</AssemblyOriginatorKeyFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Nullable>annotations</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.1" />
    <PackageReference Include="System.DirectoryServices.Protocols" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\linqtoldap_logo_small.png" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>